### ISSUE TITLE
Highlighting text description of code elements when hovering makes them unreadable

### ISSUE THREAD

**Issue by lucascherzer** [mikasius/zed-nord-theme#11] opened 2024-08-27 11:14 UTC
The highlight color is the same as the background color and not transparent
No highlighting:
<img width="476" alt="Screenshot 2024-08-27 at 13 12 21" src="https://github.com/user-attachments/assets/ccf5753d-2bff-403f-9934-96f8041f3cc2">
When highlighting:
<img width="476" alt="Screenshot 2024-08-27 at 13 13 31" src="https://github.com/user-attachments/assets/ad66adea-45a3-4f6d-9f25-0c561b823b3c">

**Comment by hedgieinsocks** [comment] 2024-08-28 06:22
I have managed to kinda fix it via the following override in the main config:

```json
  "experimental.theme_overrides": {
    "players": [
      {
        "selection": "#434c5e99"
      }
    ]
  }

**Comment by hedgieinsocks** [comment] 2024-08-28 08:13
Yes, this override will affect all other themes.  As for fixing it in the theme, I will leave it to the maintainer or someone more knowledgeable or dedicated, since it's likely to involve tweaking the colors in other players. My anxiety and ocd kicks in when I see so many parameters to test :D

**Comment by mikasius** [comment] 2024-09-16 08:04
@lucascherzer 
Will plan to do it later. Thanks for your suggestion and help!

**Comment by mikasius** [comment] 2024-09-18 05:10
@lucascherzer 
I couldn't reproduce it in a new Zed version (Zed 0.152.4)
It's works fine 🤷🏻‍♂️
![Screenshot 2024-09-18 at 12 06 56](https://github.com/user-attachments/assets/51b0f658-b703-4314-ad6a-0d59d3cb1350)

Maybe it was fixed in a new version. Could you please check? Try to update Zed.

**Comment by hedgieinsocks** [comment] 2024-09-18 05:17
Please try to select some text from the popup to see the issue. On your screenshot there is no selection inside the popup.

**Closed** 2024-09-19 04:13 UTC

**Comment by mikasius** [comment] 2024-09-19 04:27
In PR https://github.com/zed-industries/extensions/pull/1437 
Thanks guys!

**Comment by lucascherzer** [comment] 2024-09-19 09:22
I'm also running 0.152.4 and updated the extension. Highlighted text still has the same colour as the background and no transparency:
<img width="776" alt="image" src="https://github.com/user-attachments/assets/7a1e7ee8-b484-4d15-91cd-b465052fa281">

**Comment by mikasius** [comment] 2024-09-19 09:39
@lucascherzer 
Yeap, let's wait a little :)

**Comment by hedgieinsocks** [comment] 2024-09-23 17:29
It's a matter of taste, but with 0.0.9 the cursor became barely distinguishable from the background, so I had to force `"cursor": "#6e91bf"` for the first player ;D
